set(_CATKIN_CURRENT_PACKAGE "canary_lidar")
set(canary_lidar_VERSION "0.0.0")
set(canary_lidar_MAINTAINER "vboxuser <vboxuser@todo.todo>")
set(canary_lidar_PACKAGE_FORMAT "2")
set(canary_lidar_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(canary_lidar_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(canary_lidar_BUILDTOOL_DEPENDS "catkin")
set(canary_lidar_BUILDTOOL_EXPORT_DEPENDS )
set(canary_lidar_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(canary_lidar_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(canary_lidar_TEST_DEPENDS )
set(canary_lidar_DOC_DEPENDS )
set(canary_lidar_URL_WEBSITE "")
set(canary_lidar_URL_BUGTRACKER "")
set(canary_lidar_URL_REPOSITORY "")
set(canary_lidar_DEPRECATED "")